### ISSUE TITLE
"Shall I buy a computer?" doesn't match with the correct rule.

### ISSUE THREAD

**Issue by mrmechko** [mrmechko/IMDocumentation#9]
The sentence "Shall I buy a computer?" should be a perfect match to the rule below, however it only gets 0.89.

```
---
# Shall x !v1?
/ Shall I buy a computer?
(
(ONT::SPEECHACT ?v SA_YN-QUESTION :CONTENT ?!v1)
(ONT::F ?!v1 ONT::SITUATION-ROOT ::TENSE ONT::FUT :MODALITY (:* FUTURE SHALL))
)
---
```
Instead it matches with a score of 0.92 against:

```
---
# (can/could/would/will) you help me do X
/ Can you help me study?
(
(ONT::SPEECHACT ?V7187 SA_YN-QUESTION :CONTENT ?!v1)
(ONT::F ?!v1 (:* ONT::HELP ?!help) :FORMAL ?!theme :AFFECTED ?!v2 :AGENT ?!v3)
(ONT::PRO ?!v2 (:* ONT::PERSON ONT::ME))
(ONT::PRO ?!v3 (:* ONT::PERSON ONT::YOU))
)
---
```

**Comment by mrmechko** [comment]
On closer inspection, I've verified that the matching for the first rule is correct.  However, I'm noticing that there are elements being returned in the mapping that shouldn't be there:

```
 {Term<FUT>: Term<FUT>,
  Term<FUTURE SHALL>: Term<FUTURE SHALL>,
  Variable<?!v1>: Term<V46020>,
  Variable<?v>: Term<V46138>}
```

**Comment by yliu134** [comment]
I think the parse of "shall I buy a computer" does not have "ONT::SITUATION-ROOT", and that's why it is not scored 1.
As for the non-variables in the mapping, I'll modify it on my branch.

**Comment by mrmechko** [comment]
I see.  Would it be possible to have some diagnosis messages (eg what parts of the rules matched and didn't?)  That would make life a lot easier when it comes time to actually build the rules.  I can write some of the connecting code and some of the frontend, but actually a little webserver that allows us to write rules into the page and then see how they match against parses would be phenomenal.
